### ISSUE TITLE
Build with imgui 1.89.6

### ISSUE THREAD

**Issue by 2376780283** [JJL772/source-2013-imgui#6]
[zzh@localhost source-engine]$ python ./waf build -j16 -p imgui
Build commands will be stored in build/compile_commands.json
Waf: Entering directory `/home/zzh/apps/source-engine/build'
[2227/2232][99%][/][========================================================================================> ][8.978s]../imgui/imgui_impl_source.cpp:166:2: error: unknown type name 'ImGuiPlatformIO'
  166 |         ImGuiPlatformIO &platform_io = ImGui::GetPlatformIO();
      |         ^
../imgui/imgui_impl_source.cpp:166:33: error: no member named 'GetPlatformIO' in namespace 'ImGui'; did you mean 'GetPlatformExt'?
  166 |         ImGuiPlatformIO &platform_io = ImGui::GetPlatformIO();
      |                                        ^~~~~~~~~~~~~~~~~~~~
      |                                        GetPlatformExt
../public/tier0/platform.h:1460:20: note: 'GetPlatformExt' declared here
 1460 | inline const char *GetPlatformExt( void )
      |                    ^
../imgui/imgui_impl_source.cpp:254:9: error: cannot initialize return object of type 'ImFileHandle' (aka '__sFILE *') with an rvalue of type 'FileHandle_t' (aka 'void *')
  254 |         return g_pFullFileSystem->Open( filename, mode );
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.

../imgui/imgui_system.cpp:475:15: error: use of undeclared identifier 'ImGuiCol_TabSelected'
  475 |         style.Colors[ImGuiCol_TabSelected]           = ImVec4(0.23f, 0.23f, 0.24f, 1.00f);
      |                      ^
../imgui/imgui_system.cpp:476:15: error: use of undeclared identifier 'ImGuiCol_TabDimmed'; did you mean 'ImGuiCol_TabHovered'?
  476 |         style.Colors[ImGuiCol_TabDimmed]                 = ImVec4(0.08f, 0.08f, 0.09f, 1.00f);
      |                      ^~~~~~~~~~~~~~~~~~
      |                      ImGuiCol_TabHovered
../imgui/../thirdparty/imgui/imgui.h:1556:5: note: 'ImGuiCol_TabHovered' declared here
 1556 |     ImGuiCol_TabHovered,
      |     ^
../imgui/imgui_system.cpp:477:15: error: use of undeclared identifier 'ImGuiCol_TabDimmedSelected'
  477 |         style.Colors[ImGuiCol_TabDimmedSelected]     = ImVec4(0.13f, 0.14f, 0.15f, 1.00f);
      |                      ^
../imgui/imgui_system.cpp:484:15: error: use of undeclared identifier 'ImGuiCol_NavCursor'
  484 |         style.Colors[ImGuiCol_NavCursor]             = ImVec4(0.26f, 0.59f, 0.98f, 1.00f);
      |                      ^
4 errors generated.

[2231/2231][100%][-][=======================================================================================>][11.571s]
Waf: Leaving directory `/home/zzh/apps/source-engine/build'
Build failed
 -> task in 'imgui' failed with exit status 1 (run with -v to display more information)
 -> task in 'imgui' failed with exit status 1 (run with -v to display more information)
[zzh@localhost source-engine]$
